# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 5, 54, 50, 428535, tzinfo=utc)),
        ),
    ]
