# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170614_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 6, 22, 15, 652886, tzinfo=utc)),
        ),
    ]
